broker.id=1
zookeeper.connect=zookeeper:2181

# Настройка listeners для SSL
listeners=SSL://0.0.0.0:9093
advertised.listeners=SSL://localhost:9093
inter.broker.listener.name=SSL
listener.security.protocol.map=SSL:SSL

# SSL настройки
ssl.keystore.location=/opt/kafka/certs/broker1/broker1.keystore.jks
ssl.keystore.password=changeit
ssl.key.password=changeit
ssl.truststore.location=/opt/kafka/certs/broker1/broker1.truststore.jks
ssl.truststore.password=changeit
ssl.client.auth=required

# Настройка авторизации
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
allow.everyone.if.no.acl.found=false
super.users=User:CN=kafka-admin

# для брокеров 2 и 3 меняю только broker.id (2 и 3), порты (9094 и 9095) и пути к сертификатам
